function GUI_Island
%% ********************Graphical User Interface****************************
%% *********Maximum Greatest Island based on Genetic Algorithm************** 

close all;
clear all;
clc;

%Colors for controls 
panel_color=[0.55 0.75 0.65];
entryField_color=[1 1 1];
p_color=[0.5 0.5 0.5];
But_color=[0.2 0.8 0.5];
Result_color=[0.8 0.5 0.9];

%********************Handles & Controls Define****************************

%main figure contain main panel
hFigure=figure(...
    'Units','Pixels',...
    'Position',[100 100 550 400],...
    'Toolbar','none',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Color',[.5 .5 .5],...
    'Name','Image Classification Neural-Genetic');

%main panel contain all controls
hPanel=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[0 0 550 400],...
    'BackgroundColor',panel_color);

hGAl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 370 210 20],...
    'String','Genetic Algorithm Parameters',...
    'BackgroundColor',p_color);

hPopsz=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 340 100 25],...
    'String','200',...
    'BackgroundColor',entryField_color);

hPopszl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 340 100 17],...
    'String','Population Size',...
    'BackgroundColor',panel_color);

hMuRt=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 310 100 25],...
    'String','0.85',...
    'BackgroundColor',entryField_color);

hMuRtl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 310 100 17],...
    'String','Mutation Rate',...
    'BackgroundColor',panel_color);

hMu1Rt=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 280 100 25],...
    'String','0.85',...
    'BackgroundColor',entryField_color);

hMu1Rtl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 280 100 17],...
    'String','Second Mutation Rate',...
    'BackgroundColor',panel_color);

hCoRt=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 250 100 25],...
    'String','0.9',...
    'BackgroundColor',entryField_color);

hCoRtl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 250 100 17],...
    'String','Crossover Rate',...
    'BackgroundColor',panel_color);

hGen=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 220 100 25],...
    'String','50',...
    'BackgroundColor',entryField_color);

hGenl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 220 110 17],...
    'String','Number of Generation',...
    'BackgroundColor',panel_color);


hGARsl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 190 100 20],...
    'String','Genetic Result',...
    'BackgroundColor',p_color);

hGToF=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 160 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hGToFl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 160 100 17],...
    'String','Num of Blue in Island',...
    'BackgroundColor',panel_color);
%*******************************************
hNePrl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 370 210 20],...
    'String','Program Parameters',...
    'BackgroundColor',p_color);

hNuIm=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 340 100 25],...
    'String','100',...
    'BackgroundColor',entryField_color);

hNuIml=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[355 340 100 17],...
    'String','Number of All Points',...
    'BackgroundColor',panel_color);

hBlue=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 310 100 25],...
    'String','50',...
    'BackgroundColor',entryField_color);

hBluel=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[355 310 100 17],...
    'String','Num of Blues',...
    'BackgroundColor',panel_color);
hlink=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 250 200 17],...
    'String','Size of Space = 100*100',...
    'BackgroundColor',entryField_color);
hGARsl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[300 190 120 20],...
    'String','First Algorithm Result',...
    'BackgroundColor',p_color);
hFR=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[300 160 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hFRl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[405 160 120 17],...
    'String','Num of Blues in Island',...
    'BackgroundColor',panel_color);

hRand=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 120 150 17],...
    'String','Randomly Generate Points',...
    'Value',1,...
    'BackgroundColor',panel_color);
hNRand=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 100 150 17],...
    'String','Methodical Generate Points',...
    'Value',0,...
    'BackgroundColor',panel_color);
hNBlsR=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 50 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hNBlsRl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 70 120 17],...
    'String','Num of All Blue Points',...
    'BackgroundColor',panel_color);
hButton=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[285 10 150 25],...
    'String','Genetic Algorithm Start',...
    'BackgroundColor',But_color,...
    'Callback',@Start_GA_callback);

hButton1=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[285 40 150 25],...
    'String','First Algorithm Start',...
    'BackgroundColor',But_color,...
    'Callback',@Start_First_callback);

hButton2=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[285 70 150 25],...
    'String','Both Algorithms Start',...
    'BackgroundColor',But_color,...
    'Callback',@Start_Both_callback);

handles=[hButton2,hButton1,hButton,hFR,hRand,hNRand...
    hNuIm,hGToF,hGen,hCoRt,hMuRt,hPopsz,hNBlsR];
set(handles,...
    'Units','Normalized');
%% ******************** Callbacks  ****************************************

%first button callback for run genetic algorithm
    function Start_GA_callback(hObject,eventdata)
        tic();
        Gen=str2double(get(hGen,'String'));
        Pc=str2double(get(hCoRt,'String'));
        Pm=str2double(get(hMuRt,'String'));
        Pm1=str2double(get(hMu1Rt,'String'));
        Popsize=str2double(get(hPopsz,'String'));
        N_Pts=str2double(get(hNuIm,'String'));
        N_Bls=str2double(get(hBlue,'String'));
        if get(hRand,'Value')==1
            rand_gen=1;
        else
            rand_gen=0;
        end
        [N_Bls_Island_GA,~,num_blue]=main(Gen,Pc,Pm,Pm1,Popsize,N_Pts,N_Bls,rand_gen,1);
        time=toc();
        set(hGToF,'String',num2str(N_Bls_Island_GA));
        set(hFR,'String',num2str(0));
        set(hNBlsR,'String',num2str(num_blue));
    end

%second button callback for run first algorithm
    function Start_First_callback(hObject,eventdata)
        tic();
        Gen=str2double(get(hGen,'String'));
        Pc=str2double(get(hCoRt,'String'));
        Pm=str2double(get(hMuRt,'String'));
        Pm1=str2double(get(hMu1Rt,'String'));
        Popsize=str2double(get(hPopsz,'String'));
        N_Pts=str2double(get(hNuIm,'String'));
        N_Bls=str2double(get(hBlue,'String'));
        if get(hRand,'Value')==1
            rand_gen=1;
        else
            rand_gen=0;
        end
        [~,N_Bls_Island,num_blue]=main(Gen,Pc,Pm,Pm1,Popsize,N_Pts,N_Bls,rand_gen,2);
        time=toc();
        set(hFR,'String',num2str(N_Bls_Island));
        set(hGToF,'String',num2str(0));
        set(hNBlsR,'String',num2str(num_blue));
    end

% third button callback for run main first and genetic algorithms
    function Start_Both_callback(hObject,eventdata)
        tic();
        Gen=str2double(get(hGen,'String'));
        Pc=str2double(get(hCoRt,'String'));
        Pm=str2double(get(hMuRt,'String'));
        Pm1=str2double(get(hMu1Rt,'String'));
        Popsize=str2double(get(hPopsz,'String'));
        N_Pts=str2double(get(hNuIm,'String'));
        N_Bls=str2double(get(hBlue,'String'));
        if get(hRand,'Value')==1
            rand_gen=1;
        else
            rand_gen=0;
        end
        [N_Bls_Island_GA,N_Bls_Island,num_blue]=main(Gen,Pc,Pm,Pm1,Popsize,N_Pts,N_Bls,rand_gen,3);
        time=toc();
        set(hFR,'String',num2str(N_Bls_Island));
        set(hGToF,'String',num2str(N_Bls_Island_GA));
        set(hNBlsR,'String',num2str(num_blue));
    end

%**************************************************************************
%********************************End Function GUI**************************
end
%**************************************************************************
%******************************************************************************************************************************